---
title: "lit_review_brainstorm + writing"
output: html_document
---

### 1. Pertinent Variables + Brain Structures

Codebook: <https://docs.abcdstudy.org/latest/documentation/imaging/type_smri.html>

ABCD Study:

-   Structural MRI Data

    -   Amygdala Volume (R/L Hemispheres)

        -   `mr_y_smri_vol_aseg_ag_lh_sum`

        -   `mr_y_smri_vol_aseg_ag_rh_sum`

    -   Anterior Cingulate Cortex (ACC) Thickness

    -   Pre-Frontal Cortex (PFC) Thickness/Volume

-   Resting State fMRI Data

    -   Amygdala-PFC Connectivity

    -   ACC Network Connectivity

### 2. Brain Dump

Brain structures for review: pre-frontal cortex, amygdala, anterior cingulate circuit

What does each do + how are they connected?

Pre-Frontal Cortex:

Amygdala:

Anterior Cingulate Circuit:

How Can I relate this to what I want my future research to look like?

I'm interested in neurodegenerative diseases and medication resistant disorders. These both encompass chronic inflammation of neurons. Therefore, my present literature review can discuss how adversity (specifically abuse, poverty, malnutrition, etc) leads to degradation/inflammation of key brain structures (PFC, Amygdala, ACC). This degradation contributes to systemic neuroinflmmation that predisposes individuals to medication resistant conditions

### 3. Research Question

To what extent does childhood adversity-induced structural atrophy in the PFC-ACC-Amygdala circuit serve as a biomarker for chronic neuroinflammation and as a predictor of medication-resistant psychopathology?

-   In discussion/conclusion: if we can identify this PFC-ACC-Amygdala atrophy early, we can flag these individuals as being at high risk for the chronic inflammation and predisposes individuals to medication resistance and neurodegenerative disorders.

**RQ:** How does childhood poverty and abuse and adverse childhood experiences correlate with structural atrophy in the PFC-ACC-Amygdala circuit during early adolescence?

**RQ:**

specifically link to childhood

How do adverse childhood experiences (poverty, parental incarceration, low SES) correlate to structural atrophy in the PFF-ACC-Amygdala circuit and what implications does this have for adolescent and adult outcomes?

**RQ:** How does parental incarceration predict accelerated structural atrophy in the Frontolimbic circuit during early adolescence, and can these changes serve as neurobiological markers for long-term health vulnerability?

OR

**RQ (shortened):** How does parental incarceration predict accelerated structural atrophy in the Frontolimbic circuit (PFC-ACC-Amygdala) during early adolescence?

OR

**RQ:** How does parental incarceration predict structural atrophy/change in the frontolimbic circuit (PFC-ACC-Amygdala) during early adolescence?

-   identifying whether parental incarceration acts as a sufficiently significant stressor and "embeds" itself into the brain

parental incarceration + "threat" pathway -\> amygdala

-   attachment trauma

-   loss of caregiver causes amygdala hyper-reactivity

does parental incarceration lead to ACC thinning?

### 4. Preliminary Source List
