---
title: "Preliminary Source List + Thoughts"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

How does parental incarceration predict structural atrophy /change in
the Frontolimbic circuit (PFC-ACC-Amygdala) during early adolescence?

1.  Cohodes, E. M., Kitt, E. R., Baskin‐Sommers, A., & Gee, D. G.
    (2020). Influences of early‐life stress on frontolimbic circuitry:
    Harnessing a dimensional approach to elucidate the effects of
    heterogeneity in stress exposure. Developmental Psychobiology,
    63(2), 153–172. <https://doi.org/10.1002/dev.21969>
2.  Piekarski, D. J., Colich, N. L., & Ho, T. C. (2023). The effects of
    puberty and sex on Adolescent White Matter Development: A systematic
    review. Developmental Cognitive Neuroscience, 60, 101214.
    <https://doi.org/10.1016/j.dcn.2023.101214>
3.  Shaul, M., Whittle, S., Dehestani, N., Silk, T. J., &
    Vijayakumar, N. (2026). Dimensional adversity, brain-age, & mental
    health: Differences in male and female adolescents. Developmental
    Cognitive Neuroscience, 78.
    <https://doi.org/10.1016/j.dcn.2026.101671>
4.  Rakesh, D., Elzeiny, R., Vijayakumar, N., & Whittle, S. (2023). A
    longitudinal study of childhood maltreatment, subcortical
    development, and subcortico-cortical structural maturational
    coupling from early to late adolescence. Psychological Medicine,
    53(16), 7525–7536. <https://doi.org/10.1017/s0033291723001253>
5.  Swartz, J. R., Carrasco, M., Wiggins, J. L., Thomason, M. E., &
    Monk, C. S. (2014). Age-related changes in the structure and
    function of prefrontal cortex–amygdala circuitry in children and
    adolescents: A multi-modal imaging approach. NeuroImage, 86,
    212–220. <https://doi.org/10.1016/j.neuroimage.2013.08.018>
6.  Korom, M., Valadez, E. A., Tottenham, N., Dozier, M., &
    Spielberg, J. M. (2024). Preliminary examination of the effects of
    an early parenting intervention on amygdala-orbitofrontal cortex
    resting-state functional connectivity among high-risk children: A
    randomized clinical trial. Development and Psychopathology, 37(1),
    384–392. <https://doi.org/10.1017/s0954579423001669>
7.  Mills, K. L., Goddings, A.-L., Herting, M. M., Meuwese, R.,
    Blakemore, S.-J., Crone, E. A., Dahl, R. E., Güroğlu, B., Raznahan,
    A., Sowell, E. R., & Tamnes, C. K. (2016). Structural Brain
    Development between childhood and adulthood: Convergence across four
    longitudinal samples. NeuroImage, 141, 273–281.
    <https://doi.org/10.1016/j.neuroimage.2016.07.044>
8.  Valadez, E. A., Tottenham, N., Korom, M., Tabachnick, A. R.,
    Pine, D. S., & Dozier, M. (2024). A randomized controlled trial of a
    parenting intervention during infancy alters amygdala-prefrontal
    circuitry in middle childhood. Journal of the American Academy of
    Child & Adolescent Psychiatry, 63(1), 29–38.
    <https://doi.org/10.1016/j.jaac.2023.06.015>
9.  Duffy, K. A., Wiglesworth, A., Roediger, D. J., Island, E.,
    Mueller, B. A., Luciana, M., Klimes-Dougan, B., Cullen, K. R., &
    Fiecas, M. B. (2025). Characterizing the effects of age, puberty,
    and sex on variability in resting-state functional connectivity in
    late childhood and early adolescence. NeuroImage, 313.
    <https://doi.org/10.1016/j.neuroimage.2025.121238>
10. Brieant, A., Vannucci, A., Nakua, H., Harris, J., Lovell, J. R.,
    Brundavanam, D., Tottenham, N., & Gee, D. G. (2023). Characterizing
    the dimensional structure of early-life adversity in the Adolescent
    Brain Cognitive Development (ABCD) study. Developmental Cognitive
    Neuroscience, 61. <https://doi.org/10.31234/osf.io/2mkpf>
11. Gunatilake, N., Boyes, A., Elwyn, R., Brunet, A., Hermens, D. F., &
    Driver, C. (2025). Adolescent brain development following early life
    stress: A systematic review of white matter alterations from
    diffusion tensor imaging studies. Adolescent Research Review, 10(4),
    593–640. <https://doi.org/10.1007/s40894-025-00263-5>
12. Antonacci, C., Buthmann, J. L., Uy, J. P., Khosravi, P., Lee, Y., &
    Gotlib, I. H. (2025). Frontolimbic connectivity and threat‐related
    psychopathology: A data‐driven test of models of early adversity.
    Developmental Psychobiology, 67(5).
    <https://doi.org/10.1002/dev.70080>
13. Thijssen, S., Collins, P., & Luciana, M. (2020). Pubertal
    development mediates the association between family environment and
    brain structure and function in childhood. Development and
    Psychopathology, 32, 687–702.
    <https://doi.org/10.31234/osf.io/4wekz>
14. Thijssen, S., Muetzel, R. L., Bakermans-Kranenburg, M. J.,
    Jaddoe, V. W., Tiemeier, H., Verhulst, F. C., White, T., & Van
    Ijzendoorn, M. H. (2017). Insensitive parenting may accelerate the
    development of the amygdala–medial prefrontal cortex circuit.
    Development and Psychopathology, 29, 505–518.
    <https://doi.org/10.1017/s0954579417000141>
15. Pollok, T. M., Kaiser, A., Kraaijenvanger, E. J., Monninger, M.,
    Brandeis, D., Banaschewski, T., Eickhoff, S. B., & Holz, N. E.
    (2022). Neurostructural traces of early life adversities: A
    meta-analysis exploring age- and adversity-specific effects.
    Neuroscience & Biobehavioral Reviews, 135.
    <https://doi.org/10.1016/j.neubiorev.2022.104589>
16. Pantell, M. S., Silveira, P. P., de Mendonça Filho, E. J., Wing, H.,
    Brown, E. M., Keeton, V. F., Pokhvisneva, I., O’Donnell, K. J.,
    Neuhaus, J., Hessler, D., Meaney, M. J., Adler, N. E., &
    Gottlieb, L. M. (2024). Associations between social adversity and
    biomarkers of inflammation, stress, and aging in children. Pediatric
    Research, 95(6), 1553–1563.
    <https://doi.org/10.1038/s41390-023-02992-6>
17. Rincón-Cortés, M., & Sullivan, R. M. (2014). Early life trauma and
    attachment: Immediate and enduring effects on neurobehavioral and
    stress axis development. Frontiers in Endocrinology, 5(33).
    <https://doi.org/10.3389/fendo.2014.00033>
18. McLaughlin, K. A., Sheridan, M. A., & Lambert, H. K. (2014).
    Childhood adversity and neural development: Deprivation and threat
    as distinct dimensions of early experience. Neuroscience &
    Biobehavioral Reviews, 47, 578–591.
    <https://doi.org/10.1016/j.neubiorev.2014.10.012>
19. Andersen, S. L. (2022). Neuroinflammation, early-life adversity, and
    Brain Development. Harvard Review of Psychiatry, 30(1), 24–39.
    <https://doi.org/10.1097/hrp.0000000000000325>
20. Kahn, G., Bounoua, N., Strickland, J. C., Hung, I-T., Maher, B.,
    Rabinowitz, J. A., & Felton, J. W. (2026). Identifying significant
    environmental predictors of change in delay discounting among
    adolescents in the Adolescent Brain Cognitive Development Study.
    Experimental and Clinical Psychopharmacology. Advance online
    publication. <https://dx.doi.org/10.1037/pha0000851>
21. Miguel, P. M., Pereira, L. O., Silveira, P. P., & Meaney, M. J.
    (2019). Early environmental influences on the development of
    children’s brain structure and function. Developmental Medicine &
    Child Neurology, 61(10), 1127–1133.
    <https://doi.org/10.1111/dmcn.14182>
22. Bush, N. R., Wakschlag, L. S., LeWinn, K. Z., Hertz-Picciotto, I.,
    Nozadi, S. S., Pieper, S., Lewis, J., Biezonski, D., Blair, C.,
    Deardorff, J., Neiderhiser, J. M., Leve, L. D., Elliott, A. J.,
    Duarte, C. S., Lugo-Candelas, C., O’Shea, T. M., Avalos, L. A.,
    Page, G. P., & Posner, J. (2020). Family environment,
    Neurodevelopmental Risk, and the environmental influences on Child
    Health Outcomes (ECHO) initiative: Looking back and moving forward.
    Frontiers in Psychiatry, 11(547), 1–17.
    <https://doi.org/10.3389/fpsyt.2020.00547>
23. Marques-Feixa, L., Palma-Gudiel, H., Romero, S., Moya-Higueras, J.,
    Rapado-Castro, M., Castro-Quintas, Á., Zorrilla, I., José Muñoz, M.,
    Ramírez, M., Mayoral, M., Mas, A., José Lobato, M.,
    Blasco-Fontecilla, H., Fañanás, L., & EPI-Young Stress GROUP.
    (2021). Childhood maltreatment disrupts hpa-axis activity under
    basal and stress conditions in a dose–response relationship in
    children and adolescents. Psychological Medicine, 53(3), 1060–1073.
    <https://doi.org/10.1017/s003329172100249x>
24. Hardi, F. A., Goetschius, L. G., Peckins, M. K., Brooks-Gunn, J.,
    McLanahan, S. S., McLoyd, V., Lopez-Duran, N. L., Mitchell, C.,
    Hyde, L. W., & Monk, C. S. (2022). Differential developmental
    associations of material hardship exposure and adolescent
    amygdala–prefrontal cortex white matter connectivity. Journal of
    Cognitive Neuroscience, 34(10), 1866–1891.
    <https://doi.org/10.1162/jocn_a_01801>
25. Watson, S., Owen, B. M., Gallagher, P., Hearn, A. J., Young, A. H.,
    & Ferrier, I. N. (2007). Family history, early adversity and the
    hypothalamic-pituitary-adrenal (HPA) axis: Mediation of the
    vulnerability to mood disorders. Neuropsychiatric Disease and
    Treatment, 3(5), 647–653.
26.  Machlin, L., Egger, H. L., Stein, C. R., Navarro, E.,
    Carpenter, K. L. H., Goel, S., Patel, K. K., Copeland, W. E., &
    Sheridan, M. A. (2023). Distinct associations of deprivation and
    threat with alterations in brain structure in early childhood.
    Journal of the American Academy of Child & Adolescent Psychiatry,
    62(8). <https://doi.org/10.1016/j.jaac.2023.02.006>
27. Beck, D., Whitmore, L., MacSweeney, N., Brieant, A., Karl, V., de
    Lange, A.-M. G., Westlye, L. T., Mills, K. L., & Tamnes, C. K.
    (2025). Dimensions of early-life adversity are differentially
    associated with patterns of delayed and accelerated brain
    maturation. Biological Psychiatry, 97(1), 64–72.
    <https://doi.org/10.1016/j.biopsych.2024.07.019>
28. Fleck, L., Buss, C., Bauer, M., Stein, M., Mekle, R., Kock, L.,
    Klawitter, H., Godara, M., Ramler, J., Entringer, S., Endres, M., &
    Heim, C. (2025). Early‐life adversity predicts markers of
    aging‐related neuroinflammation, neurodegeneration, and cognitive
    impairment in women. Annals of Neurology, 97(4), 642–656.
    <https://doi.org/10.1002/ana.27161>
29. Arditti, J. A. (2012). Child trauma within the context of parental
    incarceration: A family process perspective. Journal of Family
    Theory & Review, 4(3), 181–219.
    <https://doi.org/10.1111/j.1756-2589.2012.00128.x>
30. Poehlmann-Tynan, J., & Turney, K. (2021). A developmental
    perspective on children with incarcerated parents. Child Development
    Perspectives, 15(1), 3–11. <https://doi.org/10.1111/cdep.12392>
31. Muentner, L., Kapoor, A., Weymouth, L., & Poehlmann‐Tynan, J.
    (2021). Getting under the skin: Physiological stress and witnessing
    paternal arrest in young children with incarcerated fathers.
    Developmental Psychobiology, 63(5), 1568–1582.
    <https://doi.org/10.1002/dev.22113>
32. Muentner, L., Fanning, K., Pritzl, K., Kapoor, A., Weymouth, L.,
    Krishnan, C. A., & Poehlmann, J. (2025). Parental incarceration,
    attachment to caregivers, and young children’s physiological stress.
    Developmental Psychobiology, 67(5).
    <https://doi.org/10.1002/dev.70076>
33. Del Toro, J., Fine, A., & Wang, M.-T. (2022). The intergenerational
    effects of paternal incarceration on children’s social and
    psychological well-being from early childhood to adolescence.
    Development and Psychopathology, 35(2), 558–569.
    <https://doi.org/10.1017/s0954579421001693>
34. Bush, N. R., Wakschlag, L. S., LeWinn, K. Z., Hertz-Picciotto, I.,
    Nozadi, S. S., Pieper, S., Lewis, J., Biezonski, D., Blair, C.,
    Deardorff, J., Neiderhiser, J. M., Leve, L. D., Elliott, A. J.,
    Duarte, C. S., Lugo-Candelas, C., O’Shea, T. M., Avalos, L. A.,
    Page, G. P., & Posner, J. (2020). Family environment,
    Neurodevelopmental Risk, and the environmental influences on Child
    Health Outcomes (ECHO) initiative: Looking back and moving forward.
    Frontiers in Psychiatry, 11(547), 1–17.
    <https://doi.org/10.3389/fpsyt.2020.00547>
35. Johnson, E. I., Planalp, E. M., Williams, D. T., & Poehlmann, J.
    (2024). Parental incarceration and health risks in a
    population-based study of U.S. early adolescents: Results among
    racialized groups. SSM - Population Health, 27.
    <https://doi.org/10.1016/j.ssmph.2024.101702>
36. Sheridan, M. A., & McLaughlin, K. A. (2022). Introduction to the
    special issue on childhood adversity and Neurodevelopment.
    Developmental Cognitive Neuroscience, 54.
    <https://doi.org/10.1016/j.dcn.2022.101082>
37. Austin, M. K., White, I. M., & Kim, A. W. (2022). Parental
    incarceration and child physical health outcomes from infancy to
    adulthood: A critical review and multilevel model of potential
    pathways. American Journal of Human Biology, 34(5).
    <https://doi.org/10.1002/ajhb.23691>
38. Sadikova, E., Weissman, D. G., Rosen, M. L., Robinson, E.,
    Lengua, L. J., Sheridan, M. A., Tiemeier, H., & McLaughlin, K. A.
    (2025). Identifying cognitive, affective, and developmental
    mechanisms linking threat and deprivation with adolescent
    psychopathology. Journal of Child Psychology and Psychiatry, 66(5),
    612–623. <https://doi.org/10.1111/jcpp.14067>
39. Miller, J. G., Ho, T. C., Humphreys, K. L., King, L. S.,
    Foland-Ross, L. C., Colich, N. L., Ordaz, S. J., Lin, J., &
    Gotlib, I. H. (2020). Early life stress, frontoamygdala
    connectivity, and biological aging in adolescence: A longitudinal
    investigation. Cerebral Cortex, 30(7), 4269–4280.
    <https://doi.org/10.1093/cercor/bhaa057>

-   4/5 Main Segments

    -   Foundational Work Identifying the Early Life Adversity/Stress
        Framework (Deprivation and/or Threat)

    -   Specifically Identifying Parental Incarceration as a stressor
        (specific section on parental incarceration)

    -   What does typical/normal neurostructural and neurobiological
        development look like in early adolescence?

    -   Biological (Neurostructural + Neurobiological) Implications of
        Early Life Adversity

    -   Tying everything together -\> what is my proposed framework
        Implications (aka my interests)

        -   Gene mapping

        -   biomarkers + indicators of neuroinflammation

        -   predisposition towards neurodegenerative disease
